# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: job1
  steps:
  - script: echo Hello from JOB1!
    displayName: 'Run a one-line script changed'

  - script: |
      echo Add other tasks to build, test, and deploy your project from JOB1.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

- job: job2
  dependsOn: job1
  steps:
  - script: echo Hello, JOB2!
    displayName: 'Run a one-line script changed'

  - script: |
      echo Add other tasks to build, test, and deploy your project from JOB2.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

- job: job3
  dependsOn: job2
  steps:
    - script: echo Hello, from JOB3
      displayName: Echo From Job3
