trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Firstjob
    steps: 
    - bash: echo Build FirstJob
    - bash: echo $(PIPELINE_LEVEL_VARIABLE)
    variables:
      environment: Dev
- stage: DevDeploy
  jobs:
  - job: Secondjob
    steps: 
    - bash: echo DevDeploy SecondJob
- stage: QaDeploy
  jobs:
  - job: Thirdjob
    steps: 
    - bash: echo QaDeploy ThirdJob
- stage: ProdDeploy
  jobs:
  - job: Fourthjob
    steps: 
    - bash: echo ProdDeploy FourthJob