# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      os: 'ubuntu-latest'
    mac: 
      os: 'macos-latest'  #os is a variable
pool:
  vmImage: $os

steps:
- script: echo Hello, world from $os
  displayName: 'Run a one-line script'

