# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# strategy:
#   matrix:
#     linux:
#       os: 'ubuntu-latest'
#     mac: 
#       os: 'macos-latest'  #os is a variable
pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: 
        steps:
          - bash: echo "Build the server"
  - stage: DevDeploy
    jobs:
    - deployment: Deployment_to_Dev_Environment
      environment: Dev
      strategy:
        runOnce:
          deploy:
            steps:
              - bash: echo deploy to Dev

  - stage: QADeploy
    jobs:
    #   - job:
    #     steps:
    #       - bash: echo "Start QA Deploy"

    - deployment: QADeployJob
      environment: QA
      strategy:
        runOnce:
          deploy:
            steps:
              - bash: echo Deploy to QA
          