# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

steps:
  - script: echo K8s Terraform Azure!!
    displayName: 'Run a one line script'
  - task: DownloadSecureFile@1
    name: publickey
    inputs:
      secureFile: 'azure_rsa.pub'

  - task: TerraformCLI@0
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
      #commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_keys=(publickey.secureFile)'
      backendType: 'azurerm'
      backendServiceArm: 'azure-resource-manager-service-connection'
      ensureBackend: true
      backendAzureRmResourceGroupName: 'terraform-backend-rg'
      backendAzureRmResourceGroupLocation: 'westeurope'
      backendAzureRmStorageAccountName: 'terraformstorageapurv'
      backendAzureRmContainerName: 'terraformbackendstoragecontainer'
      backendAzureRmKey: 'kubernetes-dev.tfstate'
  - task: TerraformCLI@0
    inputs:
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
      commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_keys=(publickey.secureFile)'
      environmentServiceName: 'azure-resource-manager-service-connection'
      commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_keys=(publickey.secureFile)'
      